/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 planter.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planter.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bergenia_Rotblum_Set065.geometry} material={materials['Sunflower_sf1hcdvf2.003']} scale={14.407} />
      <mesh geometry={nodes.Bergenia_Rotblum_Set067.geometry} material={materials['Sunflower_sf1hcdvf2.003']} scale={14.407} />
      <mesh geometry={nodes.Bergenia_Rotblum_Set069.geometry} material={materials['Sunflower_sf1hcdvf2.003']} scale={14.407} />
      <mesh geometry={nodes.Bergenia_Rotblum_Set070.geometry} material={materials['Sunflower_sf1hcdvf2.003']} scale={14.407} />
      <mesh geometry={nodes.Circle032.geometry} material={materials['Material.002']} scale={14.407} />
      <mesh geometry={nodes.Circle033.geometry} material={materials['Material.001']} scale={14.407} />
    </group>
  )
}

useGLTF.preload('/planter.glb')
